# Generated by Django 3.2.25 on 2025-04-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='ControlledBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.CharField(default='None', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LeadingAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=40, unique=True)),
                ('engines_id', models.CharField(default='None', max_length=40)),
                ('transmission_id', models.CharField(default='None', max_length=40)),
                ('leading_axle_id', models.CharField(default='None', max_length=40)),
                ('controller_bridge_id', models.CharField(default='None', max_length=40)),
                ('supply_contract', models.CharField(max_length=40)),
                ('shipping_date', models.DateField()),
                ('consignee', models.CharField(default='None', max_length=40)),
                ('delivery_address', models.CharField(default='None', max_length=40)),
                ('equipment', models.CharField(default='None', max_length=80)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.client')),
                ('controller_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.controlledbridge')),
                ('engines_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.engine')),
                ('leading_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.leadingaxle')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.CharField(default='None', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.CharField(default='None', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40, unique=True)),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Manager', 'Manager'), ('Client', 'Client'), ('ServiceCompany', 'ServiceCompany')], max_length=20)),
                ('token', models.CharField(default='Gz9fa8f4gn3F6olkBa00O3s81tkDQT', max_length=40, unique=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silant.client')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('development', models.IntegerField(default=0)),
                ('order_number', models.CharField(default='None', max_length=40, unique=True)),
                ('order_date', models.DateField()),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany')),
                ('service_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.serviceview')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany'),
        ),
        migrations.AddField(
            model_name='machine',
            name='technic_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.technic'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.transmission'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refusal_date', models.DateField()),
                ('development', models.IntegerField(default=0)),
                ('description_node', models.TextField(default='None')),
                ('spare_parts', models.CharField(default='None', max_length=60)),
                ('recovery_date', models.DateField()),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.failurenode')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.machine')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany')),
            ],
        ),
    ]
