export interface MachineModel {
        client: number,
        consignee: string,
        controller_bridge_id: string,
        controller_bridge_model: number,
        delivery_address: string,
        engines_id: string,
        engines_model: number,
        equipment: string,
        leading_axle_id: string,
        leading_axle_model: number,
        machine_id: string,
        service_company: number,
        shipping_date: string,
        supply_contract: string,
        technic_model: number,
        transmission_id: string,
        transmission_model: number,
}